In [10]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

#Each array has attributes ndim (the number of dimensions), 
#shape (the size of each dimension), and size (the total size of the array):
print('x3.ndim:', x3.ndim)
print('x3.shape:', x3.shape)
print('x3.size:', x3.size)

# Another interesting tipe - dtype (data type)

print('x3.dtype:', x3.dtype)
x3

x3.ndim: 3
x3.shape: (3, 4, 5)
x3.size: 60
x3.dtype: int64


array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [5]:
# Other attributes include itemsize, which lists the size (in bytes) of each array element,
# and nbytes, which lists the total size (in bytes) of the array
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]


5

In [10]:
x1[-1]

9

In [11]:
x1[-2]

7

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0]

array([3, 5, 2, 4])

In [14]:
x2[0,0]

3

In [15]:
x2[0,2]

2

In [16]:
x2[2,0]

1

In [18]:
#Values can also be modified using any of the above index notation:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [20]:
#Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. 
#This means, for example, that if you attempt to insert a floating-point value to an integer array, 
#the value will be silently truncated. Don't be caught unaware by this behavior!
x1[0] = 3.14
x1

array([3, 0, 3, 3, 7, 9])

In [22]:
#Just as we can use square brackets to access individual array elements, we can also use them to access s
#ubarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows 
#that of the standard Python list; 
#to access a slice of an array x, use this: x[start:stop:step]
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:5] # первые 5 элементов

array([0, 1, 2, 3, 4])

In [24]:
x[5:]

array([5, 6, 7, 8, 9])

In [25]:
x[4:7]

array([4, 5, 6])

In [26]:
x[::2]

array([0, 2, 4, 6, 8])

In [27]:
x[:8:2]

array([0, 2, 4, 6])

In [28]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [30]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [31]:
x2[:2, :3]


array([[12,  5,  2],
       [ 7,  6,  8]])

In [33]:
x2[:3, ::2]


array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [35]:
x2[2:3, ::]


array([[1, 6, 7, 7]])

In [36]:
x2[::-1, ::-1]


array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [40]:
print(x2[:, 0])


[12  7  1]


In [45]:
print(x2[:, 2])


[2 8 7]


In [46]:
print(x2[0])  # equivalent to x2[0, :]


[12  5  2  4]


In [47]:
x2_sub = x2[:2, :2]
print(x2_sub)


[[12  5]
 [ 7  6]]


In [48]:
x2_sub[0,0] = 99
x2_sub


array([[99,  5],
       [ 7,  6]])

In [49]:
x2 # В отличие от скиска Python, массив NumPy не создает копию списка, а возвращает представления списка
# c изменениями


array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
# для копиравания в этом случае есть функция copy():
x2_sub_copy = x2_sub.copy()


In [51]:
print(x2_sub_copy)


[[99  5]
 [ 7  6]]


In [57]:
# И если мы сейчас изменим x2_sub_copy, x2_sub останентся без изменений:
x2_sub_copy[0,0] = 33
x2_sub_copy


array([[33,  5],
       [ 7,  6]])

In [58]:
x2_sub


array([[99,  5],
       [ 7,  6]])

In [62]:
grib = np.arange(1, 10).reshape((3,3))
print(grib)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))


array([[1, 2, 3]])

In [65]:
x[np.newaxis, :]


array([[1, 2, 3]])

In [66]:
x[:, np.newaxis]


array([[1],
       [2],
       [3]])

In [67]:
x.reshape((3, 1))


array([[1],
       [2],
       [3]])

In [12]:
# объединение массивов - Concatenation of arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])


array([1, 2, 3, 3, 2, 1])

In [69]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [70]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])


In [71]:
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([grid, grid], axis = 1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [76]:
#For working with arrays of mixed dimensions, 
#it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:
x = np.array([1,2,3])
grid = ([[3,4,6],
        [7,8,9]])
np.vstack([x, grid])

array([[1, 2, 3],
       [3, 4, 6],
       [7, 8, 9]])

In [78]:
y = np.array([[99],
             [99]])
np.hstack([grid,y])

array([[ 3,  4,  6, 99],
       [ 7,  8,  9, 99]])

In [79]:
#Similary, np.dstack will stack arrays along the third axis.

In [80]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [15]:
#Notice that N split-points, leads to N + 1 subarrays. 
#The related functions np.hsplit and np.vsplit are similar:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
upper, lower = np.vsplit(y, [2])


In [17]:
print(upper, lower)


[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [84]:
left, right = np.hsplit(y, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [85]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#Similarly, np.dsplit will split arrays along the third axis.